package com.maangalabs.prayer;

import android.widget.TimePicker;

public class AllVar {
	public static String scname[]={
		
		"Adi Shankara Institute of Engineering & Technology Ernakulam",
		"Al-Azhar College of Engineering & Technology Thodupuzha",
		"Academy of Medical Sciences",
		"Ahalia Ayurveda Medical College",
		"National Institute of Technology",
		"Santhigiri Siddha Medical College",
		"Albertian Institute of Science and Technology",
		"Al-Azhar Dental College",
		"AWH Engineering College",
		"Ahalia School of Engineering & Technology Palakkad",
		"Azeezia College of Dental Sciences & Research Kollam",
		"Athurasramam NSS Homoeopathic Medical College Kottayam",
		"Annoor Dental College Muvattupuzha",
		"St Thomas College of Engineering",
		"Sri Sankara Dental College",
		"Calicut University Institute of Engineering & Technology Malappuram",
		"Azeezia Institute of Medical Sciences & Research Kollam",
		"Baselios Thomas I Catholicose College of Engineering & Technology Ernakulam",
		"Shahul Hameed Memorial Engineering College",
		"Pankajakasthuri College of Engineering & Technology Thiruvananthapuram",
		"Amala Institute of Medical Sciences",
		"Century International Institute of Dental Sciences & Research Kasaragod",
		"Baselios Mathews II College of Engineering",
		"Caarmel Engineering College",
		"Cochin Medical College",
		"College of Engineering",
		"Ammini College of Engineering",
		"Cochin College of Engineering & Technology",
		"Bishop Jerome Institute",
		"College of Engineering",
		"College of Engineering & Management",
		"St. Thomas Institute of Science & Technology Kazhakkoottam",
		"VimalJyothi Engineering College",
		"SUT Academy of Medical Sciences",
		"College of Engineering",
		"College of Agriculture",
		"College of Engineering",
		"Sree Narayana Institute of Ayurvedic Studies & Research Kollam",
		"Sree Narayana Guru College of Engineering & Technology",
		"College of Engineering & Technology",
		"College of Engineering",
		"College of Architecture",
		"College of Engineering",
		"Holy Kings College of Engineering and Technology Moovattupuzha Ernakulam",
		"College of Dairy Science & Technology",
		"College of Engineering",
		"CUSAT College of Engineering Pulinkunnu",
		"College of Engineering",
		"College of Fisheries",
		"Younus College of Engineering for Women Kottarakkara",
		"Ilahia College of Engineering & Technology Muvatupuzha",
		"Pallakad institute of scine and technology",
		"College of Engineering",
		"Govt. Dental College",
		"College of Engineering",
		"CUSAT College of Engineering Thrikkakara ",
		"Ilahia School of Science & Technology",
		"College of Forestry",
		"College of Engineering",
		"Govt. Medical College",
		"College of Engineering",
		"Dr. Padiyar Memorial Homoeopathic Medical College Chottanikkara",
		"Younus Institute of Technology",
		"Indira Gandhi Institute of Dental Sciences Kothamangalam",
		"College of Horticulture",
		"College of Veterinary and Animal Sciences",
		"Gurudeva Institute of Science & Tech.",
		"College of Engineering",
		"Federal Institute of Science & Technology",
		"Valia Koonambaikulathamma College of Engg.& Technology Parippally",
		"Indira Gandhi Institute of Engineering & Technology for women",
		"College of Veterinary and Animal Sciences",
		"DM Wayanad Institute of Medical Sciences",
		"Kottayam Institute of Technology & Science",
		"College of Engineering",
		"Holy Crescent College of Architecture",
		"Islamic Learning Mission College of Engineering",
		"Govt. Engineering College",
		"Educare Institute of Dental Science",
		"Mangalam College of Engineering",
		"College of Engineering",
		"K R Gouri Amma College of Engineering for Women",
		"Younus College of Engineering & Technology",
		"Jai Bharath College of Management & Engineering Technology Perumbavoor",
		"Govt. Engineering College",
		"Eranad Knowledge City Technical Campus",
		"College of Engineering",
		"Pinnacle School of Engineering & Technology Areeplachy",
		"KMEA College of Architecture",
		"Sarabhai Institute of Science & Technology",
		"P N Panicker Souhruda Ayurveda Medical College Anandhashram",
		"Govt. Medical College",
		"Global Institute of Architecture",
		"Pushpagiri College of Dental Science",
		"Dr. Somervell Memorial CSI Medical College Karakonam",
		"KMEA Engineering College",
		"Vidya Academy of Science & Technology",
		"Mar Athanasius College of Engineering",
		"Holy Grace Academy of Engineering for Women",
		"Government Ayurveda College",
		"Pushpagiri Institute of Medical Science & Research Centre",
		"Government Ayurveda College ",
		"KVM College of Engineering & Information Technology Kothamangalam",
		"Travancore Medical College",
		"Mar Baselios Christian College of Engineering & Technology Idukki",
		"IES College of Architecture",
		"Government Homoeopathic Medical College",
		"Rajiv Gandhi Institute of Technology",
		"Government Homoeopathic Medical College",
		"Malankara Orthodox Syrian Church Medical College",
		"T.K.M. College of Engineering",
		"Mar Baselios Dental College",
		"IES College of Engineering",
		"Govt. College of Engineering",
		"Saintgits College of Engineering",
		"Govt. Dental College",
		"Matha College of Technology",
		"Travancore Engineering College",
		"Mar Baselios Institute of Technology & Science Kothamangalam",
		"Jawaharlal College of Engineering & Technology",
		"Govt. Dental College",
		"St.Josephs College of Engineering & Technology",
		"Govt. Engineering College",
		"MES College of Engineering & Technology",
		"Trinity College of Engineering",
		"Mookambika Technical Campus",
		"Jubilee Mission Medical College & Research Institute Trissur",
		"Govt. Engineering College",
		"Govt. Medical College",
		"HAPPY CHRISTMAS",
		"Model Engineering College",
		"University College of Engineering",
		"Nangelil Ayurveda Medical College",
		"Jyothi Engineering College",
		"Govt. Engineering College",
		"Heera College of Engineering & Technology Nedumangadu",
		"Mount Zion College of Engineering for Women Chengannoor",
		"School of Architecture",
		"Malabar College of Engineering & Tech.",
		"Govt. Medical College",
		"Hindustan College of Engineering",
		"Muthoot Institute of Technology & Science",
		"St. Gregorios Dental College",
		"MET's School of Engineering",
		"Govt. Medical College",
		"Indian Institute of Space and Technology",
		"Rajagiri School of Engineering and Technology",
		"University College of Engineering",
		"N.S.S. College of Engineering",
		"Kelappaji College of Agril. Engineering & Technology",
		"John Cox Memorial CSI Institute of Technology",
		"SCMS School of Engineering & Technology",
		"Viswajyothi College of Engineering & Technology",
		"Nehru College of Engineering & Research Centre",
		"KMCT Ayurveda Medical College",
		"LBS Institute of Technology for Women",
		"Sree Buddha College of Engineering",
		"Nirmala College of Engineering",
		"KMCT College of Architecture",
		"Lourdes Matha College of Science & Technology",
		"Sree Narayana Guru Institute of Science & Technology",
		"PNNM Ayurveda Medical College",
		"KMCT College of Architecture",
		"M.G. College of Engineering",
		"Sree Narayana Gurukulam College of Engineering",
		"Prime College of Engineering",
		"KMCT College of Engineering for Women",
		"Mannam Ayurveda Co-operative Medical College",
		"Sree Narayana Institute of Medical Sciences",
		"PSM College of Dental Science and Research",
		"KMCT College of Engineering",
		"Mar Baselious College of Engineering & Technology Thiruvananthapuram",
		"Sree Narayana Mangalam Institute of Management & Technology",
		"Royal College of Engineering & Technology",
		"KMCT Medical College",
		"Marian Engineering College",
		"Sri. Vellappally Natesan College of Engineering",
		"Royal Dental College",
		"LBS College of Engineering",
		"MES Institute of Technology & Management",
		"St. Thomas College of Engineering & Tech.",
		"Sree Gokulam Medical College & Research Foundation",
		"Sadguru Swamy Nithyananda Institute of Technology",
		"Mohandas College of Engineering & Technology",
		"T D Medical College",
		"Santhigiri Ayurveda Medical College",
		"Malabar Dental College and Research Centre",
		"Mount Zion College of Engineering",
		"Toc H Institute of Science & Technology",
		"Sneha College of Architecture",
		"Malabar Institute of Technology",
		"Musaliar College of Engineering & Technology",
		"Vijnan Institute of Science & Technology",
		"Sree Ernakulathappan College of Engineering & Management",
		"Malabar Medical College Hospital & Research Centre",
		"Musaliar College of Engineering",
		"Sreepathy Institute of Management & Tech.",
		"MEA Engineering College",
		"Muslim Association College of Engineering",
		"Thejus Engineering College",
		"MES College of Architecture",
		"Noorul Islam College of Dental Science",
		"Universal Engineering College",
		"MES College of Engineering",
		"Pankajakasthuri Ayurveda Medical College",
		"Vaidyaretnam Ayurveda College",
		"MES Dental College",
		"PRS College of Engineering & Tech.",
		"Vidya Academy of Science & Technology",
		"MES Medical College",
		"Rajadhani Institute of Engineering & Technology Attingal",
		"Vishnu Ayurveda College",
		"Ace College of Engineering",
		"Amal Jyothi College of Engineering",
		"North Malabar Institute of Technology",
		"UKF College of Engineering & Technology",
		"KMP College of Engineering",
		"Archana College of Engineering",
		"Parassinikkadavu Ayurveda Medical College",
		"Cochin Institute of Science & Technology",
		"Aryanet Institute of Technology",
		"Sree ChitraThirunal College of Engineering",
		"Pariyaram Dental College",
		"Sahrdaya College of Engineering & Technology Kodakara",
		"M Dasan Institute of Technology",
		"Govt. Engineering College",
		"Axis College of Engineering & Technology",
		"Sree Narayana Institute of Technology",
		"St Gregorios College of Engineering Devalokam Perla",
		"Sree Vidhyadhiraja Homoeopathic Medical College",
		"Christ Knowledge City",
		"Al-Ameen Engineering College",
		"Veda Vyasa Institute of Technology",
		"Government Ayurveda College",
		"Sree Buddha College of Engineering for Women",
		"College of Agriculture",
		"VPSV Ayurveda College",
		"T K M Institute of Technology",
		"Karuna medical college",
		"Govt Medical College",
		"Palakkad Institute Of Science And Technology",
		"Medical Engineering Students Team",
		"North Subregion, South Subregion",
		"Eastern Subregion, North Central Subregion",
		"South Central Subregion, Central Subregion",
		"All Campuses in Kerala",
		"All College Teachers",
		"Calicut University,Cochin University of Science & Technology",
		"Kannur University, Kerala University",
		"Mahatma Gandhi University, Kerala University of Health Sciences",
		"The 250th Day"
	};
	public static String cname[]={"Adi Shankara Institute of Engineering & Technology Ernakulam",
		"Al-Azhar College of Engineering & Technology Thodupuzha",
		"Academy of Medical Sciences, Pariyaram, Kannur",
		"Ahalia Ayurveda Medical College, Elippara, Palakkad",
		"National Institute of Technology,Calicut",
		"Santhigiri Siddha Medical College, Santhigiri, Thiruvananthapuram",
		"Albertian Institute of Science and Technology, Kochi",
		"Al-Azhar Dental College, Thodupuzha, Idukki",
		"AWH Engineering College, Kuttikkattoor, Kozhikode",
		"Ahalia School of Engineering & Technology Palakkad",
		"Azeezia College of Dental Sciences & Research Kollam",
		"Athurasramam NSS Homoeopathic Medical College Kottayam",
		"Annoor Dental College Muvattupuzha, Ernakulam",
		"St Thomas College of Engineering,Sivapuram,Kannur",
		"Sri Sankara Dental College, Akathumuri, Varkala, Thiruvananthapuram",
		"Calicut University Institute of Engineering & Technology Malappuram",
		"Azeezia Institute of Medical Sciences & Research Kollam",
		"Baselios Thomas I Catholicose College of Engineering & Technology Ernakulam",
		"Shahul Hameed Memorial Engineering College, Kadakkal, Kollam",
		"Pankajakasthuri College of Engineering & Technology Thiruvananthapuram",
		"Amala Institute of Medical Sciences, Amala Nagar, Thrissur",
		"Century International Institute of Dental Sciences & Research Kasaragod",
		"Baselios Mathews II College of Engineering, Sasthamcotta, Kollam",
		"Caarmel Engineering College, Perunad, Pathanamthitta",
		"Cochin Medical College, Kochi, Kalamassery",
		"College of Engineering, Munnar, Idukki",
		"Ammini College of Engineering, Kannampariyaram, Mankara P O, Palakkad",
		"Cochin College of Engineering & Technology, Valiyaparambu Malappuram",
		"Bishop Jerome Institute, Fathima College Road Kollam",
		"College of Engineering, Adoor, Pathanamthitta",
		"College of Engineering & Management, Punnapra, Alappuzha",
		"St. Thomas Institute of Science & Technology Kazhakkoottam",
		"VimalJyothi Engineering College, Chemperi, Kannur",
		"SUT Academy of Medical Sciences, Vattappara Thiruvananthapuram",
		"College of Engineering, Kidangoor, Kottayam",
		"College of Agriculture, Vellayani P O, Thiruvananthapuram",
		"College of Engineering, Chengannur, Alappuzha",
		"Sree Narayana Institute of Ayurvedic Studies & Research Kollam",
		"Sree Narayana Guru College of Engineering & Technology, Payyanur",
		"College of Engineering & Technology, Payyannur",
		"College of Engineering, Poonjar, Kottayam",
		"College of Architecture, Vellanad, Thiruvananthapuram",
		"College of Engineering, Pallippuram, Cherthala",
		"Holy Kings College of Engineering and Technology Moovattupuzha Ernakulam",
		"College of Dairy Science & Technology, Mannuthy,  Thrissur",
		"College of Engineering, Mandarathur P.O., Vadakara, Kozhikode",
		"CUSAT College of Engineering Pulinkunnu,Alappuzha",
		"College of Engineering, Attingal, Thiruvananthapuram",
		"College of Fisheries, N H Bye-pass Road, Panangad P O, Ernakulam",
		"Younus College of Engineering for Women Kottarakkara",
		"Ilahia College of Engineering & Technology Muvatupuzha",
		"Pallakad institute of scine and technology",
		"College of Engineering, Thalassery, Kannur",
		"Govt. Dental College, Kottayam",
		"College of Engineering, Kallooppara, Pathanamthitta",
		"CUSAT College of Engineering Thrikkakara ,Main Campus",
		"Ilahia School of Science & Technology, Muvattupuzha, Ernakulam",
		"College of Forestry, Vellanikkara, KAU P O, Thrissur",
		"College of Engineering, Trikaripur, Kasaragod",
		"Govt. Medical College, Kottayam",
		"College of Engineering, Karunagappally, Kollam",
		"Dr. Padiyar Memorial Homoeopathic Medical College Chottanikkara",
		"Younus Institute of Technology, Kannanalloor, Nedumpana P O, Kollam",
		"Indira Gandhi Institute of Dental Sciences Kothamangalam",
		"College of Horticulture, Vellanikkara, KAU P O, Thrissur",
		"College of Veterinary and Animal Sciences, Lakkidi P O, Pookot",
		"Gurudeva Institute of Science & Tech., Vennimala Puthuppally",
		"College of Engineering, Kottarakkara, Kollam",
		"Federal Institute of Science & Technology, Angamaly, Ernakulam",
		"Valia Koonambaikulathamma College of Engg.& Technology Parippally",
		"Indira Gandhi Institute of Engineering & Technology for women, Nellikuzhi",
		"College of Veterinary and Animal Sciences, Mannuthy P O, Thrissur",
		"DM Wayanad Institute of Medical Sciences, Kalpetta, Meppadi",
		"Kottayam Institute of Technology & Science, Pallicathode, Kottayam",
		"College of Engineering, Pathanapuram, Kuriottumala, Elikattor",
		"Holy Crescent College of Architecture, South Vazhakulam, Aluva",
		"Islamic Learning Mission College of Engineering, Perumbavoor, Ernakulam",
		"Govt. Engineering College, Sreekrishnapuram, Palakkad",
		"Educare Institute of Dental Science, Kiliyamannil Campus, Chattiparamba",
		"Mangalam College of Engineering, Ettumanoor, Kottayam",
		"College of Engineering, Perumon, Kollam",
		"K R Gouri Amma College of Engineering for Women, Cherthala",
		"Younus College of Engineering & Technology, Vadakkevila, Kollam",
		"Jai Bharath College of Management & Engineering Technology Perumbavoor",
		"Govt. Engineering College, Thrissur",
		"Eranad Knowledge City Technical Campus,Cherukulam",
		"College of Engineering, Thiruvananthapuram",
		"Pinnacle School of Engineering & Technology Areeplachy",
		"KMEA College of Architecture, Kuzhivelipadi, Edathala, Aluva.",
		"Sarabhai Institute of Science & Technology, Vellanad",
		"P N Panicker Souhruda Ayurveda Medical College Anandhashram",
		"Govt. Medical College, Thrissur",
		"Global Institute of Architecture, Peradikunnu",
		"Pushpagiri College of Dental Science, Thiruvalla",
		"Dr. Somervell Memorial CSI Medical College Karakonam",
		"KMEA Engineering College, Edathala, Aluva",
		"Vidya Academy of Science & Technology, Technical Campus, Malackal",
		"Mar Athanasius College of Engineering, Kothamangalam, Ernakulam",
		"Holy Grace Academy of Engineering for Women, Mala, Kuruvilassery",
		"Government Ayurveda College, Medical College P O, Pariyaram",
		"Pushpagiri Institute of Medical Science & Research Centre, Thiruvalla",
		"Government Ayurveda College , G P O, Thiruvananthapuram",
		"KVM College of Engineering & Information Technology Kothamangalam",
		"Travancore Medical College, Mylapore, Umayanalloor P O, Kollam",
		"Mar Baselios Christian College of Engineering & Technology Idukki",
		"IES College of Architecture, Chittilappilli, Thrissur",
		"Government Homoeopathic Medical College, Karaparamba",
		"Rajiv Gandhi Institute of Technology, Pampady, Kottayam",
		"Government Homoeopathic Medical College, Iranimuttam, Manacaud",
		"Malankara Orthodox Syrian Church Medical College, Kolenchery",
		"T.K.M. College of Engineering, Kollam",
		"Mar Baselios Dental College, Kothamangalam, Ernakulam",
		"IES College of Engineering, Chittilappilly, Thrissur",
		"Govt. College of Engineering, Kannur",
		"Saintgits College of Engineering, Pathamuttom, Kottayam",
		"Govt. Dental College, Thiruvananthapuram",
		"Matha College of Technology, North Paravur, Ernakulam",
		"Travancore Engineering College, Oyoor, Ayoor, Kollam",
		"Mar Baselios Institute of Technology & Science Kothamangalam",
		"Jawaharlal College of Engineering & Technology, Mangalam,Lakkidi",
		"Govt. Dental College, Kozhikode",
		"St.Josephs College of Engineering & Technology, Palai, Choondacherry",
		"Govt. Engineering College, Barton Hill, Thiruvananthapuram",
		"MES College of Engineering & Technology, Kunnukara, Ernakulam",
		"Trinity College of Engineering, Trinity Hill, Poovada, Naruvamoodu",
		"Mookambika Technical Campus, Ettappilly, Mannathur, Muvattupuzha",
		"Jubilee Mission Medical College & Research Institute Trissur",
		"Govt. Engineering College, Kozhikode",
		"Govt. Medical College, Thiruvananthapuram",
	
		"Model Engineering College, Thrikkakara",
		"University College of Engineering, Kariavattom",
		"Nangelil Ayurveda Medical College, Nellikuzhy P O, Kothamangalam",
		"Jyothi Engineering College, Vettikkattiri P.O., Cheruthuruthy",
		"Govt. Engineering College, Mananthavady, Wayanad",
		"Heera College of Engineering & Technology Nedumangadu",
		"Mount Zion College of Engineering for Women Chengannoor",
		"School of Architecture, Mookambika Technical Campus, Etappilly",
		"Malabar College of Engineering & Tech., Deshamangalam",
		"Govt. Medical College, Kozhikode",
		"Hindustan College of Engineering, Arippa, Chozhiyakode",
		"Muthoot Institute of Technology & Science, Varokoli",
		"St. Gregorios Dental College, Chelad P O, Kothamangalam",
		"MET's School of Engineering, Mala, Thrissur",
		"Govt. Medical College, Manjeri, Malappuram",
		"Indian Institute of Space and Technology,Thiruvananthapuram",
		"Rajagiri School of Engineering and Technology, Rajagiri Valley",
		"University College of Engineering, Thodupuzha, Idukki",
		"N.S.S. College of Engineering, Akathethara P O, Palakkad",
		"Kelappaji College of Agril. Engineering & Technology, Tavanur",
		"John Cox Memorial CSI Institute of Technology, Kannammoola",
		"SCMS School of Engineering & Technology, Karukutty, Ernakulam",
		"Viswajyothi College of Engineering & Technology, Vazhakulam",
		"Nehru College of Engineering & Research Centre, Pampady",
		"KMCT Ayurveda Medical College, Manasseri P O, Mukkom",
		"LBS Institute of Technology for Women, Poojappura, Thiruvananthapuram",
		"Sree Buddha College of Engineering, Pattoor P O, Padanilam",
		"Nirmala College of Engineering, Kunnappilly, Chalakkudy",
		"KMCT College of Architecture, Kalanthode, Poolakode, Kozhikkode.",
		"Lourdes Matha College of Science & Technology, Lourdes Hills",
		"Sree Narayana Guru Institute of Science & Technology, Thekkethazham",
		"PNNM Ayurveda Medical College, Cheruthuruthy P O, Shoranur",
		"KMCT College of Architecture, Manassery, Kozhikkode.",
		"M.G. College of Engineering, Thiruvallam, Thiruvananthapuram",
		"Sree Narayana Gurukulam College of Engineering, Kolencherry",
		"Prime College of Engineering, Erattayal, Kodumbu",
		"KMCT College of Engineering for Women, Mukkam, Manassery",
		"Mannam Ayurveda Co-operative Medical College, Pandalam",
		"Sree Narayana Institute of Medical Sciences, Chalakka",
		"PSM College of Dental Science and Research, Akkikavu",
		"KMCT College of Engineering,Kallanthode, NIT Campus",
		"Mar Baselious College of Engineering & Technology Thiruvananthapuram",
		"Sree Narayana Mangalam Institute of Management & Technology",
		"Royal College of Engineering & Technology, Akkikavu",
		"KMCT Medical College, Mukkom, Kozhikode",
		"Marian Engineering College, Menamkulam, Kazhakuttom",
		"Sri. Vellappally Natesan College of Engineering, Pallikkal",
		"Royal Dental College, Iron Hills, Chalissery P O, Palakkad",
		"LBS College of Engineering, Muliyar P O, Kasaragod",
		"MES Institute of Technology & Management, Chathannoor, Kollam",
		"St. Thomas College of Engineering & Tech., Kozhuvalloor P O, Venmoney",
		"Sree Gokulam Medical College & Research Foundation, Venjaramoodu",
		"Sadguru Swamy Nithyananda Institute of Technology, Kusal Nagar",
		"Mohandas College of Engineering & Technology, Nedumangad",
		"T D Medical College, Alappuzha",
		"Santhigiri Ayurveda Medical College, Olassery P O, Kodumbu Via",
		"Malabar Dental College and Research Centre, Chekanoor Road, Mudur",
		"Mount Zion College of Engineering, Kadammanitta, Pathanamthitta",
		"Toc H Institute of Science & Technology, Arakkunnam, Ernakulam",
		"Sneha College of Architecture, Attayapathi, Govindapuram, Palakkad",
		"Malabar Institute of Technology, Anjarakandy, Kannur",
		"Musaliar College of Engineering & Technology, Kumbazha, Pathanamthitta",
		"Vijnan Institute of Science & Technology, Nellurupara, Piravom, Ernakulam",
		"Sree Ernakulathappan College of Engineering & Management, Muppliyam",
		"Malabar Medical College Hospital & Research Centre, Modakkallur",
		"Musaliar College of Engineering, Chirayinkeezhu",
		"Sreepathy Institute of Management & Tech., Vavanoor",
		"MEA Engineering College, Perinthalmanna, Malappuram",
		"Muslim Association College of Engineering, Venjaramoodu",
		"Thejus Engineering College, Vellarkkad, Erumapetti P O, Thrissur",
		"MES College of Architecture, Nedumalakkunnu, Kizhakkumuri",
		"Noorul Islam College of Dental Science, Aralummoodu, Neyyattinkara",
		"Universal Engineering College, Vallivattom P O, Konathukunnu, Thrissur",
		"MES College of Engineering, Kuttippuram, Malappuram",
		"Pankajakasthuri Ayurveda Medical College, Kattakada",
		"Vaidyaretnam Ayurveda College, Thaikkattussery P.O., Ollur",
		"MES Dental College, Perinthalmanna, Palachode",
		"PRS College of Engineering & Tech., Paliyode, Neyyattinkara",
		"Vidya Academy of Science & Technology, Thalakkottukara",
		"MES Medical College, Perinthalmanna, Malappuram",
		"Rajadhani Institute of Engineering & Technology Attingal",
		"Vishnu Ayurveda College, Govt. Press P O, Shornur, Palakkad",
		"Ace College of Engineering, Plappattivila, Karinkadamugal",
		"Amal Jyothi College of Engineering,Koovapally P.O., Kanjirapally",
		"North Malabar Institute of Technology, Kanhangad, Kasargod",
		"UKF College of Engineering & Technology, Meenambalam, Puthemkulam",
		"KMP College of Engineering, Cherukunnam, Asamanoor P O, Perumbavoor",
		"Archana College of Engineering, Palamel, Nooranad P O, Alappuzha",
		"Parassinikkadavu Ayurveda Medical College, Parassinikadavu",
		"Cochin Institute of Science & Technology, Ettappilly, Mannathur",
		"Aryanet Institute of Technology, Vadakkentekadu, Vallikadu,Mundoor",
		"Sree ChitraThirunal College of Engineering, Pappanamcode",
		"Pariyaram Dental College, Pariyaram, Kannur",
		"Sahrdaya College of Engineering & Technology Kodakara",
		"M Dasan Institute of Technology, Ulliyeri",
		"Govt. Engineering College, Painavu, Idukki",
		"Axis College of Engineering & Technology, Ambanoly, Kodakara",
		"Sree Narayana Institute of Technology, Adoor, Pathanamthitta",
		"St Gregorios College of Engineering Devalokam Perla, Kasaragod",
		"Sree Vidhyadhiraja Homoeopathic Medical College, Nemom",
		"Christ Knowledge City, Kuzhoor,Airapuram P O, Ernakulam",
		"Al-Ameen Engineering College, Shoranur, Palakkad",
		"Veda Vyasa Institute of Technology, Ponnempada",
		"Government Ayurveda College, Dhanwanthari Nagar, Tripunithura",
		"Sree Buddha College of Engineering for Women, Ayathil, Elavumthitta",
		"College of Agriculture, Padannakkad P O, Kasaragod",
		"VPSV Ayurveda College, Edarikode P O, Kottakkal, Malappuram",
		"T K M Institute of Technology, Ezhukone, Kollam",
		"Karuna medical college",
		"Govt Medical College, Painav, Idukki",
		"Palakkad Institute Of Science And Technology,Attayampathy",
		"Medical Engineering Students Team",
		"North Subregion, South Subregion",
		"Eastern Subregion, North Central Subregion",
		"South Central Subregion, Central Subregion",
		"All Campuses in Kerala",
		"All College Teachers",
		"Calicut University,Cochin University of Science & Technology",
		"Kannur University, Kerala University",
		"Mahatma Gandhi University, Kerala University of Health Sciences","All Colleges"
};
	public static String cdate[]={"18/08/2014",
		"19/08/2014",
		"20/08/2014",
		"21/08/2014",
		"22/08/2014",
		"23/08/2014",
		"24/08/2014",
		"25/08/2014",
		"26/08/2014",
		"27/08/2014",
		"28/08/2014",
		"29/08/2014",
		"30/08/2014",
		"31/08/2014",
		"01/09/2014",
		"02/09/2014",
		"03/09/2014",
		"04/09/2014",
		"05/09/2014",
		"06/09/2014",
		"07/09/2014",
		"08/09/2014",
		"09/09/2014",
		"10/09/2014",
		"11/09/2014",
		"12/09/2014",
		"13/09/2014",
		"14/09/2014",
		"15/09/2014",
		"16/09/2014",
		"17/09/2014",
		"18/09/2014",
		"19/09/2014",
		"20/09/2014",
		"21/09/2014",
		"22/09/2014",
		"23/09/2014",
		"24/09/2014",
		"25/09/2014",
		"26/09/2014",
		"27/09/2014",
		"28/09/2014",
		"29/09/2014",
		"30/09/2014",
		"01/10/2014",
		"02/10/2014",
		"03/10/2014",
		"04/10/2014",
		"05/10/2014",
		"06/10/2014",
		"07/10/2014",
		"08/10/2014",
		"09/10/2014",
		"10/10/2014",
		"11/10/2014",
		"12/10/2014",
		"13/10/2014",
		"14/10/2014",
		"15/10/2014",
		"16/10/2014",
		"17/10/2014",
		"18/10/2014",
		"19/10/2014",
		"20/10/2014",
		"21/10/2014",
		"22/10/2014",
		"23/10/2014",
		"24/10/2014",
		"25/10/2014",
		"26/10/2014",
		"27/10/2014",
		"28/10/2014",
		"29/10/2014",
		"30/10/2014",
		"31/10/2014",
		"01/11/2014",
		"02/11/2014",
		"03/11/2014",
		"04/11/2014",
		"05/11/2014",
		"06/11/2014",
		"07/11/2014",
		"08/11/2014",
		"09/11/2014",
		"10/11/2014",
		"11/11/2014",
		"12/11/2014",
		"13/11/2014",
		"14/11/2014",
		"15/11/2014",
		"16/11/2014",
		"17/11/2014",
		"18/11/2014",
		"19/11/2014",
		"20/11/2014",
		"21/11/2014",
		"22/11/2014",
		"23/11/2014",
		"24/11/2014",
		"25/11/2014",
		"26/11/2014",
		"27/11/2014",
		"28/11/2014",
		"29/11/2014",
		"30/11/2014",
		"01/12/2014",
		"02/12/2014",
		"03/12/2014",
		"04/12/2014",
		"05/12/2014",
		"06/12/2014",
		"07/12/2014",
		"08/12/2014",
		"09/12/2014",
		"10/12/2014",
		"11/12/2014",
		"12/12/2014",
		"13/12/2014",
		"14/12/2014",
		"15/12/2014",
		"16/12/2014",
		"17/12/2014",
		"18/12/2014",
		"19/12/2014",
		"20/12/2014",
		"21/12/2014",
		"22/12/2014",
		"23/12/2014",
		"24/12/2014",
		"26/12/2014",
		"27/12/2014",
		"28/12/2014",
		"29/12/2014",
		"30/12/2014",
		"31/12/2014",
		"01/01/2015",
		"02/01/2015",
		"03/01/2015",
		"04/01/2015",
		"05/01/2015",
		"06/01/2015",
		"07/01/2015",
		"08/01/2015",
		"09/01/2015",
		"10/01/2015",
		"11/01/2015",
		"12/01/2015",
		"13/01/2015",
		"14/01/2015",
		"15/01/2015",
		"16/01/2015",
		"17/01/2015",
		"18/01/2015",
		"19/01/2015",
		"20/01/2015",
		"21/01/2015",
		"22/01/2015",
		"23/01/2015",
		"24/01/2015",
		"25/01/2015",
		"26/01/2015",
		"27/01/2015",
		"28/01/2015",
		"29/01/2015",
		"30/01/2015",
		"31/01/2015",
		"01/02/2015",
		"02/02/2015",
		"03/02/2015",
		"04/02/2015",
		"05/02/2015",
		"06/02/2015",
		"07/02/2015",
		"08/02/2015",
		"09/02/2015",
		"10/02/2015",
		"11/02/2015",
		"12/02/2015",
		"13/02/2015",
		"14/02/2015",
		"15/02/2015",
		"16/02/2015",
		"17/02/2015",
		"18/02/2015",
		"19/02/2015",
		"20/02/2015",
		"21/02/2015",
		"22/02/2015",
		"23/02/2015",
		"24/02/2015",
		"25/02/2015",
		"26/02/2015",
		"27/02/2015",
		"28/02/2015",
		"01/03/2015",
		"02/03/2015",
		"03/03/2015",
		"04/03/2015",
		"05/03/2015",
		"06/03/2015",
		"07/03/2015",
		"08/03/2015",
		"09/03/2015",
		"10/03/2015",
		"11/03/2015",
		"12/03/2015",
		"13/03/2015",
		"14/03/2015",
		"15/03/2015",
		"16/03/2015",
		"17/03/2015",
		"18/03/2015",
		"19/03/2015",
		"20/03/2015",
		"21/03/2015",
		"22/03/2015",
		"23/03/2015",
		"24/03/2015",
		"25/03/2015",
		"26/03/2015",
		"27/03/2015",
		"28/03/2015",
		"29/03/2015",
		"30/03/2015",
		"31/03/2015",
		"01/04/2015",
		"02/04/2015",
		"03/04/2015",
		"04/04/2015",
		"05/04/2015",
		"06/04/2015",
		"07/04/2015",
		"08/04/2015",
		"09/04/2015",
		"10/04/2015",
		"11/04/2015",
		"12/04/2015",
		"13/04/2015",
		"14/04/2015",
		"15/04/2015",
		"16/04/2015",
		"17/04/2015",
		"18/04/2015",
		"19/04/2015",
		"20/04/2015",
		"21/04/2015",
		"22/04/2015",
		"23/04/2015",
		"24/04/2015",
		"25/04/2015"};
	public static String ccord1[]={"Central",
		"Eastern",
		"North",
		"North Central",
		"North",
		"South",
		"Central",
		"Eastern",
		"North",
		"North Central",
		"South",
		"South Central",
		"Central",
		"North",
		"South",
		"North",
		"South",
		"Central",
		"South",
		"South",
		"North Central",
		"North",
		"South",
		"South Central",
		"Central",
		"Eastern",
		"North Central",
		"North",
		"South",
		"South",
		"Central",
		"South",
		"North",
		"South",
		"South Central",
		"South",
		"South Central",
		"South",
		"North",
		"North",
		"South Central",
		"South",
		"Central",
		"Eastern",
		"North Central",
		"North",
		"South Central",
		"South",
		"Central",
		"South",
		"Eastern",
		"North Central",
		"North",
		"South Central",
		"South Central",
		"Central",
		"Eastern",
		"North Central",
		"North",
		"South Central",
		"South",
		"Central",
		"South",
		"Eastern",
		"North Central",
		"North",
		"South Central",
		"South",
		"Central",
		"South",
		"Eastern",
		"North Central",
		"North",
		"South Central",
		"South",
		"Central",
		"Eastern",
		"North Central",
		"North",
		"South Central",
		"South",
		"Central",
		"South",
		"Eastern",
		"North Central",
		"North",
		"South",
		"South",
		"Central",
		"South",
		"North",
		"North Central",
		"North Central",
		"South Central",
		"South",
		"Central",
		"South",
		"Eastern",
		"North Central",
		"North",
		"South Central",
		"South",
		"Central",
		"South",
		"Eastern",
		"North Central",
		"North",
		"South Central",
		"South",
		"Central",
		"South",
		"Eastern",
		"North Central",
		"North",
		"South Central",
		"South",
		"Central",
		"South",
		"Eastern",
		"North Central",
		"North",
		"South Central",
		"South",
		"Central",
		"South",
		"Eastern",
		"North Central",
		"North",
		"South",
		"Central",
		"South",
		"Eastern",
		"North Central",
		"North",
		"South",
		"South Central",
		"Eastern",
		"North Central",
		"North",
		"South",
		"Central",
		"Eastern",
		"North Central",
		"North",
		"South",
		"Central",
		"Eastern",
		"North Central",
		"North",
		"South Central",
		"Central",
		"Eastern",
		"North Central",
		"North",
		"South",
		"Central",
		"North Central",
		"North",
		"South",
		"Central",
		"North Central",
		"North",
		"South",
		"Central",
		"North Central",
		"North",
		"South",
		"Central",
		"North Central",
		"North",
		"South",
		"Central",
		"North Central",
		"North",
		"South",
		"Central",
		"North Central",
		"North",
		"South",
		"Central",
		"South",
		"North",
		"South",
		"Central",
		"North Central",
		"North Central",
		"South",
		"Central",
		"North Central",
		"North",
		"South",
		"Central",
		"North Central",
		"North",
		"South",
		"North Central",
		"North",
		"South",
		"North Central",
		"North",
		"South",
		"North Central",
		"North",
		"South",
		"North Central",
		"North",
		"South",
		"North Central",
		"North",
		"South",
		"North Central",
		"South",
		"South Central",
		"North",
		"South",
		"Eastern",
		"Central",
		"North",
		"Eastern",
		"North Central",
		"South",
		"North",
		"North Central",
		"North",
		"Eastern",
		"North Central",
		"South",
		"North",
		"South",
		"Eastern",
		"North Central",
		"North",
		"Eastern",
		"South",
		"North",
		"North",
		"South",
		"North Central",
		"Eastern",
		"North Central",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		""};
	//public static String ccord[]={"Bince George","Jimmy John","Inactive Group","Mathew Sam","Gerald Joseph","Jimmy Davis","Davis George","Derrick","Sonu"
	//};
	public static int hou;
	public static int min;
	AllVar()
	{
				
	}
	
}
